#!/usr/bin/env bash
set -euo pipefail

: "${TANDEM_CONTROL_PANEL_HOST:=0.0.0.0}"
: "${TANDEM_CONTROL_PANEL_PORT:=39734}"
: "${TANDEM_ENGINE_URL:=http://tandem-engine:39733}"
: "${TANDEM_CONTROL_PANEL_AUTO_START_ENGINE:=0}"
: "${TANDEM_STATE_DIR:=/var/lib/tandem/panel}"
: "${TANDEM_CONTROL_PANEL_STATE_DIR:=/var/lib/tandem/panel/control-panel}"
: "${TANDEM_CONTROL_PANEL_CONFIG_FILE:=${TANDEM_CONTROL_PANEL_STATE_DIR}/control-panel-config.json}"
: "${TANDEM_CONTROL_PANEL_MODE:=auto}"

export TANDEM_CONTROL_PANEL_HOST
export TANDEM_CONTROL_PANEL_PORT
export TANDEM_ENGINE_URL
export TANDEM_CONTROL_PANEL_AUTO_START_ENGINE
export TANDEM_STATE_DIR
export TANDEM_CONTROL_PANEL_STATE_DIR
export TANDEM_CONTROL_PANEL_CONFIG_FILE
export TANDEM_CONTROL_PANEL_MODE

exec tandem-control-panel
